title: Boris Calderón
description: Analista Financiero | Controller
theme: jekyll-theme-cayman

# Esto crea el menú de navegación
nav:
  - name: Inicio
    link: /
  - name: Sobre mí
    link: /acercademi/
  - name: Proyectos
    link: /proyectos/
